{% set name = "aligator" %}
{% set version = environ.get('VERSION', '') %}
{% set from_tag = environ.get('FROM_TAG', '') %}

package:
  name: {{ name }}
  version: {{ version }}

source:
{% if from_tag %}
  git_url: https://github.com/Simple-Robotics/aligator
  git_rev: v{{ version }}
{% else %}
  path: ../../..
{% endif %}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aligator", max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - clang  # [win]
    - ninja
  host:
    - eigen
    - eigenpy
    - libboost-devel
    - libboost-python-devel
    - fmt
    - pinocchio
    - proxsuite-nlp>=0.8.0
    - crocoddyl # [not win]
    - python
    - matplotlib
    - llvm-openmp
    - example-robot-data
  run:
    - eigen
    - python
    - matplotlib
    - proxsuite-nlp>=0.8.0
    - typed-argument-parser

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - aligator

about:
  home: https://github.com/Simple-Robotics/aligator
  summary: A trajectory optimization library for robotics and beyond.
  license: BSD-2-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - "olivier.roussel@inria.fr"
    - "joris.vaillant@inria.fr"
